#!/bin/sh
#
# Start/stop server script
#
SERVER_NAME=touch-blink
SERVER_PATH=/usr/sbin/
#DEV_TYPE_FILE=/tmp/BrBoxDevType.txt
start() {
	echo -n "Starting $SERVER_NAME Service: "
	#DEV_TYPE=$(cat $DEV_TYPE_FILE)
	#$SERVER_PATH/$SERVER_NAME --boardtype=$DEV_TYPE &
	echo none > /sys/class/leds/ACT/trigger #touch-blink will on/off mmc0 ACT led of raspberry pi	
	$SERVER_PATH/$SERVER_NAME &
	echo "OK"
}

stop() {
	echo -n "Stopping $SERVER_NAME Service:  "
	killall $SERVER_NAME
	echo mmc0 > /sys/class/leds/ACT/trigger #revert ACT led function to show the mmc0 activity of raspberry pi	
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
